---
- name: Pull docker image and deploy 
  hosts: docker 
  become: true
  tasks:
   - name: Install Docker
     package:
        name: docker-ce
        state: present

   - name: Start Docker service
     systemd:
        name: docker
        state: started
        enabled: yes
   - name: Install pip
     become: true
     yum:
        name: python3-pip
        state: present

   - name: Install Docker Python module
     pip:
        name: docker
        state: present
   - name: Pull  image from Docker
     docker_image:
        name: learndevops083/sampleapp:latest
        source: pull
        state: present

   - name: Start Sampleimageapp container
     docker_container:
        name: mysampleapp
        image: learndevops083/sampleapp:latest
        ports:
          - "8000:8080"
        state: started
        restart_policy: unless-stopped
 
